services:
  myfarm:
    container_name: myfarm
    image: a765961515/myfarm:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.combined
    ports:
      - "8089:80"  # 前端通过Nginx访问
      - "9999:9999"  # 可选：直接访问后端（调试用）
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 代码里 ruoyi.profile 默认 /home/ruoyi/uploadPath
      - ruoyi_upload:/home/ruoyi/uploadPath

volumes:
  ruoyi_upload:

